### ISSUE TITLE
The current build fails with the following error

### ISSUE THREAD

**Issue by t2924** [sanket1729/bulletproofs-svm#2]
Starting rangeproof test for value:  3  in range from 0 to 2^ 4
Traceback (most recent call last):
  File "rangeproof.py", line 333, in <module>
    run_test_rangeproof(value, rangebits)
  File "rangeproof.py", line 292, in run_test_rangeproof
    rp.generate_proof(proofval)
  File "rangeproof.py", line 59, in generate_proof
    pc = PC(encode(self.value, 256, minlen=32), blinding=self.gamma)
  File "/home/to/joinmarket-clientserver/jmbitcoin/vectorpedersen.py", line 18, in __init__
    self.h = getNUMS(255).serialize() if not h else h
AttributeError: PublicKey instance has no attribute 'serialize'

I am a beginner.how to solve this problem.
Thanks a million!

**Comment by sanket1729** [comment]
Hey, did you try the new INSTALL instructions from README? You need the old version of joinmarket to make this work
